### ISSUE TITLE
There is no rmats files

### ISSUE THREAD

**Issue by xhhwhc** [Xinglab/rmats-turbo#106]
File "rmats.py", line 536, in <module>
    main()
  File "rmats.py", line 502, in main
    args = get_args()
  File "rmats.py", line 194, in get_args
    args.prep_prefix = claim_prep_prefix(args.task, args.tmp)
  File "rmats.py", line 482, in c
    with open(file_path, 'wt'):
OSError: [Errno 22] Invalid argument: '/media/whc/8EE21FA1E21F8D19/tmp1/2021-04-06-14:10:31_434297_0.rmats'

**Comment by EricKutschera** [comment]
rMATS is trying to create that file `2021-04-06-14:10:31_434297_0.rmats`, but it seems that file name is considered an `Invalid argument`. I think the filesystem that it's trying to write to does not support colon `:` in the file name

Since `:` is not always supported, rMATS should not use it in the filenames that it tries to create. You could edit rmats.py as done in this commit to replace `:` with `_` (https://github.com/Xinglab/rmats-turbo/commit/481574a92a9b7bc0065e56ee4f465154c4b162ba)

If you have access to another type of filesystem that allows `:`, you could try using a `--tmp` directory argument that points to that filesystem. You could check all the filesystem types on your system with `df -T` or just for that directory with `df -T /media/whc/8EE21FA1E21F8D19/tmp1/`
