### ISSUE TITLE
rmats run, with error in conda environment

### ISSUE THREAD

**Issue by RajneeshSrivastava** [Xinglab/rmats-turbo#133]
Hi rMATS Team,

I recently installed rMATS using conda environment with the below command: 
```conda install -c bioconda/label/cf201901 rmats```
 (from https://anaconda.org/bioconda/rmats)

After ~1 hr of run, its ending up with below error and no resulting output but the genomic stats.

```Traceback (most recent call last):
  File "/path/bin/rmats.py", line 308, in <module>
    main()
  File "/path/bin/rmats.py", line 289, in main
    run_stat(jc_it % ('SE'), args.tstat, 'JC', 'SE', args.cstat, args.od, args.tmp, args.stat)
  File "/path/bin/rmats.py", line 254, in run_stat
    call(map(str, [rmats_c, '-i', istat, '-t', tstat, '-o', ostat % ('P-V'), '-c', cstat,]), stdout=FNULL)
  File "/path/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/path/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/path/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
srun: error: g14: task 0: Exited with exit code 1
```

Please suggest, if I am missing any dependencies or error in code (please see below)
Thanks in advance!
Rajneesh
```
source activate CondaEnv
srun rmats.py --b1 /path/CODE/rMATS_code/C.txt --b2 /path/CODE/rMATS_code/H.txt --gtf /path/Reference/mm39_E104/Mus_musculus.GRCm39.104.gtf --od /path/ -t paired --readLength 100 --cstat 0.0001 --libType fr-unstranded
```

**Comment by EricKutschera** [comment]
That error looks like it is from an old bioconda version of rmats. It should be fixed in the latest version which you can get with `conda install -c conda-forge -c bioconda rmats=4.1.1`

Here is a closed issue at the bioconda recipe repo reporting a similar error: https://github.com/bioconda/bioconda-recipes/issues/12782

The conda install command you used is not recommended since it will install an old version of rmats. Unfortunately I don't have direct control over what is shown at https://anaconda.org/bioconda/rmats. I can only change the bioconda recipe: https://github.com/bioconda/bioconda-recipes/tree/master/recipes/rmats

**Comment by CharlotteAnne** [comment]
When I install with `conda install -c conda-forge -c bioconda rmats=4.1.1`
I get error:
```
Traceback (most recent call last):
  File "/camp/home/capitac/miniconda3/bin/rmats.py", line 19, in <module>
    from rmatspipeline import run_pipe
ModuleNotFoundError: No module named 'rmatspipeline'
```

**Comment by CharlotteAnne** [comment]
Sorry! Found my answer in "Conda rmatspipeline #67" - was not running with the correct python installation.
