### ISSUE TITLE
rMATS result: lots of reads clipped

### ISSUE THREAD

**Issue by huangwb8** [Xinglab/rmats-turbo#144]
Hi~
After using tools such as MISO, SUPPA2 and VAST-TOOLS, I think rMATS is the best and the most friendly one. 

My code looks like: 
```
nohup python ${rmats} \
    --b1 ${path_rmats_res}/DM.txt \
    --b2 ${path_rmats_res}/DB.txt \
    --gtf ${path_gtf} \
    -t paired \
    --libType fr-secondstrand --readLength 150 \
    --variable-read-length \
    --novelSS --mil 50 --mel 500 \
    --nthread 20 \
    --od ${path_rmats_res}/DM.vs.DB \
    --tmp ${path_rmats_res}/DM.vs.DB/tmp \
    > ${path_rmats_log}/rmats_DM.vs.DB.log 2>&1 &
```

Here is the content of `summary.txt`, which seems normal. 
```
EventType       TotalEventsJC   TotalEventsJCEC SignificantEventsJC     SigEventsJCSample1HigherInclusion SigEventsJCSample2HigherInclusion        SignificantEventsJCEC   SigEventsJCECSample1HigherInclusion     SigEventsJCECSample2HigherInclusion
SE      92664   93327   3863    2225    1638    4037    2326    1711
A5SS    34271   34379   661     350     311     700     368     332
A3SS    50780   50835   833     407     426     859     423     436
MXE     29826   30291   1732    837     895     1801    914     887
RI      17553   17609   708     334     374     822     391     431
```

In the log file, I found some discomforting descriptions:
```
USED: 177130398
NOT_PAIRED: 3005288
NOT_NH_1: 0
NOT_EXPECTED_CIGAR: 2797665
NOT_EXPECTED_READ_LENGTH: 0
NOT_EXPECTED_STRAND: 0
EXON_NOT_MATCHED_TO_ANNOTATION: 5180487
JUNCTION_NOT_MATCHED_TO_ANNOTATION: 1880803
CLIPPED: 238040944
total: 428035585
outcomes by BAM written to:...
```
Here, lots of reads were clipped during the analysis. Is it common? Or some parameters I set were wrong?
By the way, I'm sure that `-t paired --libType fr-secondstrand --readLength 150` are set correctly, which comes from the suggestion of my sequencing manufacturer.
Could you give some suggestions? Thanks a lot!

**Comment by EricKutschera** [comment]
`CLIPPED: 238040944` means that those reads had clipping operations in the input BAM files. By default rMATS filters out reads that having clipping operations.

You can use `--allow-clipping` in your command to tell rMATS to use those clipped reads. Or you could re-align your reads to create BAM files that don't have clipping operations. If you are using STAR to align the reads then you could add `--alignEndsType EndToEnd` to prevent it from generating clipped alignments.

**Comment by huangwb8** [comment]
@EricKutschera 

Thanks for quick reply!

I have test `--allow-clipping` in rMATS and it really works. I also noticed that the number of significant events increases a lot. 

I plan to figure out differential AS events and explore the protein sequence databases for isoform analysis. According to your experience, is it suitable to tell rMATS to use clipped reads or prevent aligner from generating clipped alignments? 

The parameter exists in rMATS, which means it's recommanded in some scenario but not the others. Could you give some suggestions?

> `CLIPPED: 238040944` means that those reads had clipping operations in the input BAM files. By default rMATS filters out reads that having clipping operations.
> 
> You can use `--allow-clipping` in your command to tell rMATS to use those clipped reads. Or you could re-align your reads to create BAM files that don't have clipping operations. If you are using STAR to align the reads then you could add `--alignEndsType EndToEnd` to prevent it from generating clipped alignments.

**Comment by EricKutschera** [comment]
Clipping was disabled in rMATS before I started working on the project, so I'm not entirely sure what the initial reasons were

From this post (https://groups.google.com/g/rmats-user-group/c/NmBYgPoG4TU/m/wqYIExxAEAAJ) it seems like one reason was so that the calculation for effective length normalization would be correct. Clipping the reads is similar to using shorter reads and since the read length is part of the normalization calculation, clipping could have a negative impact on that calculation

However, from this post (https://groups.google.com/g/rmats-user-group/c/ZCxjlQfP9ak/m/PaO_skpQAgAJ) we tested how rMATS performed with variable read lengths and found that the results are not very sensitive to the read length

The parameter exists because it is not 100% clear that allowing clipping is correct in all cases. But after testing it seems like it should be fine to let the aligner generate clipped alignments and then use `--allow-clipping`

**Comment by huangwb8** [comment]
Clear interpretation. Thank you very much!
