### ISSUE TITLE
the results of none repeated sample is NULL: USED:0, many reads in NOT_PAIRED and NOT_NH_1

### ISSUE THREAD

**Issue by Yichel518** [Xinglab/rmats-turbo#149]
my results are as follows:
read outcome totals across all BAMs
USED: 0
NOT_PAIRED: 26851297
NOT_NH_1: 11714073
NOT_EXPECTED_CIGAR: 1744561
NOT_EXPECTED_READ_LENGTH: 0
NOT_EXPECTED_STRAND: 0
EXON_NOT_MATCHED_TO_ANNOTATION: 37608551
JUNCTION_NOT_MATCHED_TO_ANNOTATION: 24690391
CLIPPED: 19644561
total: 122253434
outcomes by BAM written to: /home/yxtu/Data/LncRNA/Illumina/other_fishes/Anguilla_anguilla/2021-09-28-21:13:16_259311_read_outcomes_by_bam.txt

novel: 393.09977746009827
The splicing graph and candidate read have been saved into /home/yxtu/Data/LncRNA/Illumina/other_fishes/Anguilla_anguilla/2021-09-28-21:13:16_259311_*.rmats
save: 0.004146575927734375
loadsg: 0.003951072692871094

==========
Done processing each gene from dictionary to compile AS events
Found 0 exon skipping events
Found 0 exon MX events
Found 0 alt SS events
There are 0 alt 3 SS events and 0 alt 5 SS events.
Found 0 RI events

How can I do for this?
thanks a lot!

**Comment by EricKutschera** [comment]
It seems that most of the reads are not being used because of `EXON_NOT_MATCHED_TO_ANNOTATION` and `JUNCTION_NOT_MATCHED_TO_ANNOTATION`. That could happen if the reference files (.gtf, .fasta) that were used to create the input BAM(s) are not compatible with the `--gtf` argument given to rMATS

Also a lot of the reads were not used because of `CLIPPED`. You can use `--allow-clipping` in your command to tell rMATS to use those clipped reads

The numbers for the other outcomes seem reasonable: (`NOT_PAIRED`, `NOT_NH_1`, `NOT_EXPECTED_CIGAR`)

**Comment by Yichel518** [comment]
thanks a lot.
I'm testing adding `-- allow-Clipping`, but I suspect it's because Rmats can't recognize NCBI's chromosome “NC_XXXX.1”.

**Comment by EricKutschera** [comment]
rmats should handle any chromosome name as long as the name is used consistently in the input BAM and GTF. rmats has special handling to match up chromosome names that differ only by the presence or absence of an initial 'chr', but rmats does not require a 'chr' prefix: https://github.com/Xinglab/rmats-turbo/issues/102#issuecomment-807363275
