### ISSUE TITLE
Is it a misleading message in README.md or my misunderstanding ?

### ISSUE THREAD

**Issue by gnilihzeux** [Xinglab/rmats-turbo#158]
Dear author,
   Please see the picture，shouldn't the inclusion be `riExonStart_0base` and `riExonEnd` ?
  
![image](https://user-images.githubusercontent.com/4859358/141260544-905ef5ce-a137-453c-8895-abce055373d7.png)

By the way, I sorted out the information with pictures. Is there any mistake in my understanding?

![image](https://user-images.githubusercontent.com/4859358/141261433-8f2e3a3b-9edd-42ce-bc7b-23c5b6bde934.png)

Thanks for your time.

**Comment by EricKutschera** [comment]
I think the README is correct to say:
> The inclusion form includes (retains) the intron (upstreamEE, downstreamES)

Because (upstreamEE, downstreamES) is the intron (the grey exon 3 in your picture)

In your picture some of the labels for the event coordinates are not in the correct place to match the rmats output:

* SE and MXE are correct
* The picture on the middle row left side (with exon 1 and 3 touching) should have longExonStart_0base moved to the same spot as shortES
* The picture on the middle row right side should have from left to right: flankingES, flankingEE, longExonStart_0base, shortES, (both longExonEnd, shortEE at last spot)
* The RI picture should have riExonStart_0base moved to the same spot as upstreamES. riExonEnd should be moved to the same spot as downstreamEE

**Comment by gnilihzeux** [comment]
Thank you for the correction. I reorgnized it as follows.
![image](https://user-images.githubusercontent.com/4859358/141397038-00b10f09-8569-4a58-8cae-c28f0a33ca3b.png)

**Comment by lennartraman** [comment]
@EricKutschera correct me if I'm wrong, but I believe A5SS and A3SS are switched in the image above?
