### ISSUE TITLE
trouble running python rmats.py

### ISSUE THREAD

**Issue by KarimS86** [Xinglab/rmats-turbo#20]
Hi,

We can build it using this tarball, after adding library references for blas and lapack to the C Makefile. But when we try to run "python rmats.py", we get this error:

$ python rmats.py help
Traceback (most recent call last):
  File "rmats.py", line 16, in <module>
    from rmatspipeline import run_pipe
ImportError: /hpc/software/rMATS_turbo/v4.1.0/rmatspipeline.so: undefined symbol: _ZNK8BamTools12BamAlignment14SetErrorStringERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES8_

It appears to come from the bamtools source, rather than the pipeline source.   How can we fix this?

**Comment by EricKutschera** [comment]
Which tarball did you build from? Were there any error messages during compilation?

It seems like that import error might be due to different compiler versions being used for bamtools and rmatspipeline. During the build it should print which compiler is being used.

**Comment by KarimS86** [comment]
We used rmats_turbo_v4_1_0_python_3_6.tar.gz  from the latest release. 
We did not get any errors during compilation.

Are there any logs that are created during compiling? 

Thank you

**Comment by EricKutschera** [comment]
rmats_turbo_v4_1_0_python_3_6.tar.gz comes with the build artifacts and is meant to be run directly without running a build (but the pre-built versions may not be compatible with your system). If you want to run the build yourself you should start from https://github.com/Xinglab/rmats-turbo/releases/download/v4.1.0/rmats_turbo_v4_1_0.tar.gz or the latest commit on the master branch. Since the artifacts were already there, the build may have skipped some steps.

Output should be printed directly to the terminal during compilation

**Comment by EricKutschera** [comment]
The solution from this other issue may work for you: https://github.com/Xinglab/rmats-turbo/issues/21
