### ISSUE TITLE
failed test run

### ISSUE THREAD

**Issue by jamyers2358** [Xinglab/rmats-turbo#21]
I have downloaded: rmats_turbo_v4_1_0.tar.gz extracted and ran ./build_rmats --conda --no-paired-model which completed with a few warnings along the way but no noticeable errors. When I run ./test_rmats it builds the conda env with no warnings/errors but I end up with 21 failures. Do you have any recommendations?

**Comment by EricKutschera** [comment]
What do the failure messages say? Some of the tests are for the paired model which are expected to fail since you built with --no-paired-model. For the other failures you can find more info in the directory for that test. For example you could check the files in `tests/skipped_exon_basic/command_output/` for more details about the failure

**Comment by jamyers2358** [comment]
Thank you for your response. I actually tried building a few times with and without the --no-paired-model and I always received the same 21 failures upon completion of the test run. I checked a few logs as you suggested and I am seeing this: 
[command_output]$ cat rmats_stderr
Traceback (most recent call last):
  File "rmats-turbo/rmats.py", line 16, in <module>
    from rmatspipeline import run_pipe
ImportError: /rmats-turbo/rmatspipeline.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZNK8BamTools12BamAlignment14SetErrorStringERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES8_

**Comment by EricKutschera** [comment]
That looks like the same error as in https://github.com/Xinglab/rmats-turbo/issues/20 . The error seems to indicate that the bamtools library and rmatspipeline were not compiled in a compatible way.

The output to the terminal from ./build_rmats should show what compiler was used for bamtools and then for rmatspipeline. Can you post those (or redirect the build output to a file and attach that)? What OS and version are you using?

I've had errors from newer versions of gcc, but they have been at compile time and prevent the build from finishing. I have not fully tested this, but you could try the change to bamtools/CMakeLists.txt in this commit: https://github.com/Xinglab/rmats-turbo/commit/067188ab83c93b3834a2303513ade581467684bc

**Comment by jamyers2358** [comment]
Once I saw the error coming out of my logs, I recognized it as #20 my apologies for the redundancy.
Attached is a copy of two build logs. build2.log was stuff that was getting written to stdout even though I was redirecting into a file [(build.log).](url
[build.log](https://github.com/Xinglab/rmats-turbo/files/4903937/build.log)
[build2.log](https://github.com/Xinglab/rmats-turbo/files/4903938/build2.log)

) 
I am running everything on Linux version 3.10.0-957.21.3.el7.x86_64 Red Hat 4.8.5-36

**Comment by EricKutschera** [comment]
I was able to reproduce the error and found a work around.

In your build.log the compilers found for bamtools are /usr/bin/cc and /usr/bin/c++ which are both version 4.8.5

```
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working CXX compiler: /usr/bin/c++
```

Later in the build.log when it's compiling rmatspipeline it uses g++ without a specific path

```
creating build/temp.linux-x86_64-3.6/rmatspipeline
g++ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall [...]
```

It's using g++ because of this https://github.com/Xinglab/rmats-turbo/blob/master/rMATS_pipeline/setup.py#L11

```
os.environ['CC'] = 'g++'
os.environ['CXX'] = 'g++'
```

You should be able to compile by either removing those two lines or setting them to

```
os.environ['CC'] = '/usr/bin/cc'
os.environ['CXX'] = '/usr/bin/c++'
```

**Comment by jamyers2358** [comment]
Thank you for the guidance. I have been successful at building and running the tests.
