### ISSUE TITLE
how to determine whether the slicing event happens in control group or treatment group?

### ISSUE THREAD

**Issue by xinmiaoyan** [Xinglab/rmats-turbo#232]
I run rmats successfully by given b1 with control bam and b2 with treatment bam.  and I get the differential splicing event.
However, for each splicing event, we want to count how many splicing happens in control group, and how many happens in treatment group. how could I do this. appreciate it if you could give some guideline or suggestions.

**Comment by EricKutschera** [comment]
See this post: https://github.com/Xinglab/rmats2sashimiplot/issues/68

**Comment by xinmiaoyan** [comment]
Thanks Eric, that helps, but do we have any solutions to determine the splicing event frequency based on the rmats result instead of look at the figures one by one?

**Comment by EricKutschera** [comment]
I'm not sure exactly what you are trying to calculate, but the rmats output has the inclusion and skipping counts for each event in the columns like IJC_SAMPLE_1. I don't think you need to generate any plots

**Comment by xinmiaoyan** [comment]
got it, thanks. Eric. that helps! Actually, i just want to get the splicing event frequency for each groups based on the result files, for example, there're 128 SE between 2 different groups,  i want to know how many happens in group1, and how many happens in group2.

**Comment by EricKutschera** [comment]
From the post linked to before: I don't think it is clear how to classify events so that they either "happen in group 1" or "happen in group 2". If a group has inclusion reads to support the event and also skipping reads for that event then it seems like that group has the event. With that definition both groups can have the event at the same time. If you want to use that definition then you can just check to see if there are non-zero counts in both IJC_SAMPLE_1 and SJC_SAMPLE_1 to say that group 1 has the event

**Comment by xinmiaoyan** [comment]
thank you so much! Eric, I get inspired.
