### ISSUE TITLE
--limitBAMsortRAM Error 

### ISSUE THREAD

**Issue by ebonner303** [Xinglab/rmats-turbo#238]
Hi,

I am trying to run rMATS on some .fq.gz files: It is throwing an error when trying to call STAR

EXITING because of fatal ERROR: not enough memory for BAM sorting: 
SOLUTION: re-run STAR with at least --limitBAMsortRAM 68205707619

This is strange because I have already successfully aligned these files using STAR, so I am unsure why I am getting this error when trying to run them again using the rMATS wrapper. Please let me know what additional information is needed to help me sort this problem.

**Comment by EricKutschera** [comment]
Here's the command rMATS uses for STAR: https://github.com/Xinglab/rmats-turbo/blob/v4.1.2/rmats.py#L70

Here's a post on the STAR github with a similar error message: https://github.com/alexdobin/STAR/issues/289

It seems like STAR can give that error message if the input fastq files are already sorted by coordinate.

You could edit the STAR command in rMATS to use `--outSAMtype BAM Unsorted` which I think will avoid the error message. rMATS does not actually require sorted BAM files

If you already aligned the files using STAR then you could run rMATS with --b1 and --b2 to avoid aligning the files again

**Comment by rezarahman12** [comment]
Hi Erick ( @EricKutschera  )
I'm having the same problem of memory running out, "EXITING because of fatal ERROR: not enough memory for BAM sorting". So, I added --outSAMtype BAM Unsorted  flags in rMATS. 
Below is my command-

run_rmats \
--s1 s1_sam68KO.txt \
--s2 s2_sam68WT.txt \
--gtf ./Mus_musculus.GRCm39.108.gtf \
--bi ./star_mm39 \
-t paired \
--readLength 150 \
--variable-read-length \
--outSAMtype BAM Unsorted \
--novelSS \
--nthread 22 \
--od /scratch/project_mnt/S0077/AS_sam68/out \
--tmp /scratch/project_mnt/S0077/AS_sam68/out 

error now getting-
usage: rmats.py [options]
rmats.py: error: unrecognized arguments: --outSAMtype BAM Unsorted

I appreciate your time.

Kind regards
Reza
Is there any way to avoid this?

**Comment by EricKutschera** [comment]
The parameters suggested before can be given to STAR.
rmats.py (which is what run_rmats calls) does not expect those parameters: `rmats.py: error: unrecognized arguments: --outSAMtype BAM Unsorted`

You could edit the rmats.py file (https://github.com/Xinglab/rmats-turbo/blob/v4.1.2/rmats.py#L70) to change `--outSAMtype BAM SortedByCoordinate` to `--outSAMtype BAM Unsorted`

**Comment by rezarahman12** [comment]
Thanks a lot for your great help.
Best regards
Reza
