### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by Kennyluo4** [Xinglab/rmats-turbo#26]
Hello,
I'm using rMATs v.4.1.0 for my analysis. 
My input is `rmats.py --nthread 30 --b1 E4_treated.txt --b2 E4_control.txt --gtf /merged_gtf.annotated_IDmodified.gtf --od E4_result -t paired --variable-read-length --tmp tmp`

Howerver I got an python error of division by zero:

> ==========
Done processing each gene from dictionary to compile AS events
Found 25035 exon skipping events
Found 1291 exon MX events
Found 45822 alt SS events
There are 29779 alt 3 SS events and 16043 alt 5 SS events.
Found 25347 RI events
==========
>ase: 4.069897890090942
count: 23.107282400131226
Processing count files.
Traceback (most recent call last):
  File "/apps/mats/4.1.0/rMATS/rMATS_P/inclusion_level.py", line 56, in <module>
    psi2=vec2psi(inc2,skp2,effective_inclusion_length,effective_skipping_length);
  File "/apps/mats/4.1.0/rMATS/rMATS_P/inclusion_level.py", line 30, in vec2psi
    psi.append(str(round(float(inc[i])/inclusion_length/(float(inc[i])/inclusion_length+float(skp[i])/skipping_length),3)));
ZeroDivisionError: float division by zero

The bam files are sorted bam output by STAR, and the gtf file is my assembled transcripts result. How can I work around this issue? 

Thanks
Ziliang

**Comment by EricKutschera** [comment]
I think the issue is that the default --readLength of zero is being used which is causing either inclusion_length or skipping_length to be calculated as zero. Could you try again but add a value for --readLength to your command? You can use an average read length since you are also using --variable-read-length

--readLength should actually be a required argument and changes have been made in the master branch: https://github.com/Xinglab/rmats-turbo/pull/13/files

The calculations for inclusion and skipping lengths are shown here: https://github.com/Xinglab/rmats-turbo#output

The calculations depend on --readLength, --anchorLength, and the lengths of the exons. With the default readLength=0, anchorLength=1, and a small exon it looks like those values could be negative or zero. A readLength of at least twice anchorLength should give positive inclusion and skipping lengths

**Comment by Kennyluo4** [comment]
Thanks for the infomation!
It works now with the --readLength specified.
