### ISSUE TITLE
rMATS giving multiple PSI and IncLevelDifference for the same genomic region

### ISSUE THREAD

**Issue by Oliverfeudj** [Xinglab/rmats-turbo#266]
Hello I have run and obtained the results of rMATS and I have noticed that for many event there are multiple values of PSI and IncLevelDifference as well as Pvalues and FDR, why is it the case? And what shall we do to prevent this or we can choose the one with the smallest Pvalue and FDR?

Thank you for your answer
here is a table showing that 
![image](https://user-images.githubusercontent.com/52349851/222654728-becebc75-e1b9-4f63-9b70-fb25061a5821.png)

**Comment by EricKutschera** [comment]
rMATS can find multiple events that share one of the exons. It looks like your examples might be SE events where the target exon coordinates are the same (exonStart_0base exonEnd)?

For events where the target exon is the same, there should be a difference in at least one of upstreamEE or downstreamES. Those two coordinates are needed in addition to the target exon coordinates in order to define the junctions as shown in the diagram: https://github.com/Xinglab/rmats-turbo/tree/v4.1.2#output

Depending on what you are doing with the rMATS output, it might make sense to just pick 1 event for each exon with the smallest FDR

**Comment by Oliverfeudj** [comment]
Yes it is the case and that's exactly what I did for each event, I took the event with the smallest FDR and PValue, Thank you!!
