### ISSUE TITLE
rmats4.1.0  the outfile only header

### ISSUE THREAD

**Issue by Dazhuangafei** [Xinglab/rmats-turbo#268]
Hi!
I use the rmats_4.1.0 , but the outfile also only the " fromGTF." files are not empty. My data is single and short sequencing.

./run_rmats --b1 /home/wu/statistics/bam/b1.txt --b2 /home/wu/statistics/bam/b2.txt  --gtf /home/wu/statistics/genome/MSU.gtf -t single --readLength 28 --variable-read-length --nthread 4 --od /home/wu/statistics/bam/final --tmp /home/wu/statistics/bam/temp
gtf: 3.6805801391601562
There are 57016 distinct gene ID in the gtf file
There are 68103 distinct transcript ID in the gtf file
There are 50232 one-transcript genes in the gtf file
There are 319162 exons in the gtf file
There are 12865 one-exon transcripts in the gtf file
There are 12297 one-transcript genes with only one exon in the transcript
Average number of transcripts per gene is 1.194454
Average number of exons per transcript is 4.686460
Average number of exons per transcript excluding one-exon tx is 5.545041
Average number of gene per geneGroup is 5.548828
statistic: 0.014643192291259766
novel: 15.00730586051941
The splicing graph and candidate read have been saved into /home/wu/statistics/bam/temp/2023-03-10-19:06:46_392817.rmats
save: 1.0708415508270264
loadsg: 0.00699925422668457

==========
Done processing each gene from dictionary to compile AS events
Found 868 exon skipping events
Found 9 exon MX events
Found 2727 alt SS events
There are 1843 alt 3 SS events and 884 alt 5 SS events.
Found 3150 RI events
==========

ase: 0.47817349433898926
count: 1.7132608890533447
Processing count files.
Done processing count files.
(/home/wu/software/rmats/rmats-turbo/conda_envs/rmats) find -name rmats-turbo-master
(/home/wu/software/rmats/rmats-turbo/conda_envs/rmats) find -name *master
./PAIRADISE/.git/logs/refs/heads/master
./PAIRADISE/.git/refs/heads/master

And when I try to run it again , it will report an error:
There are 57016 distinct gene ID in the gtf file
There are 68103 distinct transcript ID in the gtf file
There are 50232 one-transcript genes in the gtf file
There are 319162 exons in the gtf file
There are 12865 one-exon transcripts in the gtf file
There are 12297 one-transcript genes with only one exon in the transcript
Average number of transcripts per gene is 1.194454
Average number of exons per transcript is 4.686460
Average number of exons per transcript excluding one-exon tx is 5.545041
Average number of gene per geneGroup is 5.548828
statistic: 0.014600992202758789
novel: 15.526538848876953
The splicing graph and candidate read have been saved into /home/wu/statistics/bam/temp/2023-03-10-19:23:31_728828.rmats
save: 1.020533800125122
WARNING: there are redundant temporary files.
loadsg: 0.013076305389404297

==========
Done processing each gene from dictionary to compile AS events
Found 868 exon skipping events
Found 9 exon MX events
Found 2727 alt SS events
There are 1843 alt 3 SS events and 884 alt 5 SS events.
Found 3150 RI events
==========

ase: 0.5549345016479492
./run_rmats: line 19: 11092 Segmentation fault              (core dumped) python "${SCRIPT_DIR}/rmats.py" "$@"

If you have any suggestion, I will be very grateful

**Comment by EricKutschera** [comment]
It looks like you built rmats from source since you are running with `./run_rmats`. You could try a new build from the latest master branch code which includes a fix for an issue that could cause a `Segmentation fault` error like what you posted: https://github.com/Xinglab/rmats-turbo/pull/228

`WARNING: there are redundant temporary files.` would happen on a rerun because of the old files. You can delete the old --od and --tmp directories or use new paths

If you can use at least v4.1.1 then the output would show counts of reads that were filtered out for various reasons. If a lot of your reads are filtered then that could lead to the limited output

If you run with --statoff then a particular filtering step needed for the statistical model will be skipped. With --statoff you should get some output rows and can see if the issue is that the samples have zero counts for events

**Comment by Dazhuangafei** [comment]
Thanks for your reply.  The  problem has been solved when I try to run it again.
