### ISSUE TITLE
Should upstream/downstream exons exactly match?

### ISSUE THREAD

**Issue by zhuchcn** [Xinglab/rmats-turbo#284]
Hi, thanks for developing and maintaining this tool! I have a question about the upstream downstream exons. For SE, rMATS reports the upstream and downstream exon coordinates. If a gene has multiple transcript isoforms, and some transcripts don't have the upstream exon start or downstream exon end match with what is reported by rMATS, are those transcripts not capable of carrying this SE? I'm asking this because we somehow found that sometimes, there isn't any transcript that have the upstream downstream exons match exactly. So I'm wondering how important the upstream exon start and downstream exon end are, or should we only care about the upstream exon end and downstream exon start that contribute to the actual junction.

**Comment by EricKutschera** [comment]
The upstreamES and downstreamEE don't matter so much. When rMATS works with an SE event it is mostly only using the other 4 coordinates (exonStart_0base, exonEnd, upstreamEE, downstreamES). The diagram in the README shows what reads rMATS will count toward each isoform for SE events: https://github.com/Xinglab/rmats-turbo/tree/v4.1.2#output

The upstream exon start and downstream exon end don't actually change what reads are counted. The upstreamES and downstreamEE are basically just recording which exons rMATS used to first define the event, but otherwise those 2 coordinates don't matter. Any SE events that share the other 4 coordinates should be considered as the same SE event

**Comment by zhuchcn** [comment]
Thanks for explaining! @EricKutschera Then for upstreamES, is it always the very first exon upstream to the skipped exon(s)? Or could there be other exons between the upstreamES and exonStart_0base?

**Comment by zhuchcn** [comment]
Sorry just want to clarify your last comment. If there is an exon between the upstreamES and exonStart_0base, does that mean the interjacent exon is also skipped?
