### ISSUE TITLE
can rMATS works with total RNA

### ISSUE THREAD

**Issue by huplxy** [Xinglab/rmats-turbo#294]
Hi Eric,

I am wondering that whether samples containing pre-mRNA are suitable for rMATS analysis or not.  And my guess is that the  existing of pre-mRNA would increase the intron retain events.
(my sample is from whole cell lysate and the purification procedure before RNA-seq library preparation is ribominus, which means I only discard ribosome RNA from my sample and each pre-mRNA in the nuclear were kept in my seq sample.)

Thank you!

**Comment by huplxy** [comment]
oh, another question is about the level of SigEventsJCECSample1HigherInclusion in A3SS/A5SS. I've already found some of your discussion about this in other issues:
"For SE (skipped exon) events, lower inclusion level means more of the skipping isoform which skips the exon and matches up with the name of the event. For RI (retained intron) events, higher inclusion level means more of the inclusion isoform which retains the intron and matches up with the name of the event. For the other event types (MXE, A3SS, A5SS), the name of the event does not indicate one isoform over the other"
But I don't understand, what could indicate the difference between samples in events likeMXE, A3SS and A5SS. For example, which column can indicate its higher trend in having A3SS events in treated samples comparing with control samples?
thank you!

**Comment by EricKutschera** [comment]
rMATS can work with samples containing pre-mRNA. rMATS will still count the reads, and as you said there would likely be more retained introns as compared to samples without pre-mRNA. The counts for the other event types could be affected as well

https://github.com/Xinglab/rmats-turbo/tree/v4.1.2#output shows which reads count toward which isoform for each event. Below that is a description of the event columns and for A3SS and A5SS: "The inclusion form includes the long exon (longExonStart_0base, longExonEnd) instead of the short exon (shortES shortEE)"
