### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by jeongmeani** [Xinglab/rmats-turbo#30]
Hi, 

i have installed rmats but some issues occur.

when i run cmd ./build_rmats --conda, it is done with last line 

>  ** using staged installation 
> ** R
> ** data
> *** moving datasets to lazyload DB
> ** byte-compile and prepare package for lazy loading
> ** help
> *** installing help indices
> ** building package indices
> ** testing if installed package can be loaded from temporary location
> ** testing if installed package can be loaded from final location
> ** testing if installed package keeps a record of temporary installation path
> * DONE (PAIRADISE)
>  Loading required package: PAIRADISE

and i run python rmats.py
it prints this message
`ImportError: /data/tools/rMATS_install/rmats-turbo/rmatspipeline.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZNK8BamTools12BamAlignment10GetTagTypeERKSsRc`

what can i do?

Best Regards

Jeongmin

**Comment by EricKutschera** [comment]
That error is similar to what was reported in this issue: https://github.com/Xinglab/rmats-turbo/issues/21

The problem in that case was that different compilers were being used for building bamtools and then building rmatspipeline. The fix was to change CC and CXX here: https://github.com/Xinglab/rmats-turbo/blob/master/rMATS_pipeline/setup.py#L11

Removing those lines may work or you could set them to match what is printed out during the bamtools part of the build for C and CXX compiler
