### ISSUE TITLE
p-value in the presence of NAs

### ISSUE THREAD

**Issue by lucasrocmoreira** [Xinglab/rmats-turbo#318]
Thank you for this awesome tool!

I am currently running rMATS on a dataset of five biological replicates per treatment group. I understand that whenever rMATS does not detect any reads for a certain inclusion event it adds an NA. I noticed, however, that whenever any replicate contains an NA, rMATS is not able to estimate the p-value for a certain event, which causes many genes with a significant effect to be missed. Sometimes events with very clear differences between groups are assigned a p-value of 1 because, for a single sample, there happens to be an NA. 

I was wondering if there is any strategy to ignore these NAs when estimating the p-value for a given event (considering them just like missing data). I looked up the options and couldn't find any. Maybe you have some advice on how to proceed in that case.

Thank you in advance,
Lucas

**Comment by EricKutschera** [comment]
The p-value code checks if any replicate has no reads and if so it just outputs p-value=1:
https://github.com/Xinglab/rmats-turbo/blob/v4.1.2/rMATS_C/src/util.c#L185
https://github.com/Xinglab/rmats-turbo/blob/v4.1.2/rMATS_C/src/myfunc.c#L468

This branch adds a new parameter which edits the file that would be used to calculate the p-values and for each event it drops replicates that have 0 read counts: https://github.com/Xinglab/rmats-turbo/commit/b493b251de73c9c0bc1d1efb394867164f02398c
With that change the p-value calculation just ignores replicates if they have NA inclusion levels. The change is only in the rmats.py file and if you are already using v4.1.2 or the latest master branch code then I think you should be able to just replace rmats.py with the updated file in the new commit

**Comment by lucasrocmoreira** [comment]
Thank you so much for the quick response, Eric.

I have just tested the implemented change and it works perfectly!

**Comment by Lv-haohao** [comment]
> 非常感谢您的快速回复，埃里克。
> 
> 我刚刚测试了已实施的更改，它运行良好！

Hello, it seems that you have encountered the issue of p-values being all 1. In order to better answer your question, I would need more context about what you are working on and what tool you are using.

Regarding the link provided by the author, it discusses what p-value = 1 may mean. The author suggests several possible explanations, including statistical defects or data anomalies. Additionally, the author suggests checking for multicollinearity and ensuring that the model fits the data properly.

If you need more help, please provide more relevant context information, and I will do my best to assist you.

**Comment by forever-happy-h** [comment]
> 非常感谢您的快速回复，埃里克。
> 
> 我刚刚测试了已实施的更改，它运行良好！

Hello, it seems that you have encountered the issue of p-values being all 1. In order to better answer your question, I would need more context about what you are working on and what tool you are using.

Regarding the link provided by the author, it discusses what p-value = 1 may mean. The author suggests several possible explanations, including statistical defects or data anomalies. Additionally, the author suggests checking for multicollinearity and ensuring that the model fits the data properly.

If you need more help, please provide more relevant context information, and I will do my best to assist you.

**Comment by forever-happy-h** [comment]
> 非常感谢您的快速回复，埃里克。
> 
> 我刚刚测试了已实施的更改，它运行良好！

Hello, I have also encountered the problem of p-values being all 1 and I'm wondering how you solved this issue. I'm not sure how to use the link provided by the author and I would really appreciate your help.

Thank you in advance for your assistance.

**Comment by forever-happy-h** [comment]
> p 值代码检查是否有任何复制没有读取，如果是，它只输出 p 值 = 1：https://github.com/Xinglab/rmats-turbo/blob/v4.1.2/rMATS_C/src/util.c#L185 https://github.com/Xinglab/rmats-turbo/blob/v4.1.2/rMATS_C/src/myfunc.c#L468
> 
> 此分支添加一个新参数，该参数编辑将用于计算 p 值的文件，对于每个事件，它会丢弃读取计数为 0 的重复：[b493b25](https://github.com/Xinglab/rmats-turbo/commit/b493b251de73c9c0bc1d1efb394867164f02398c) 通过该更改，p 值计算仅忽略具有 NA 包含水平的重复。更改仅在 rmats.py 文件中，如果您已经在使用 v4.1.2 或最新的主分支代码，那么我认为您应该能够在新提交中用更新的文件替换 rmats.py



> p 值代码检查是否有任何复制没有读取，如果是，它只输出 p 值 = 1：https://github.com/Xinglab/rmats-turbo/blob/v4.1.2/rMATS_C/src/util.c#L185 https://github.com/Xinglab/rmats-turbo/blob/v4.1.2/rMATS_C/src/myfunc.c#L468
> 
> 此分支添加一个新参数，该参数编辑将用于计算 p 值的文件，对于每个事件，它会丢弃读取计数为 0 的重复：[b493b25](https://github.com/Xinglab/rmats-turbo/commit/b493b251de73c9c0bc1d1efb394867164f02398c) 通过该更改，p 值计算仅忽略具有 NA 包含水平的重复。更改仅在 rmats.py 文件中，如果您已经在使用 v4.1.2 或最新的主分支代码，那么我认为您应该能够在新提交中用更新的文件替换 rmats.py

Hello, I used the new script rmats.py you provided, but the result is still all p values are 1, this is my own sample reason.

Thank you in advance

**Comment by EricKutschera** [comment]
The script removes replicates that have no read counts for the event from the statistical test. The events in your output could have p value of 1 for a different reason. For example it may be that there are too few read counts for the events, or the read counts for the two sample groups are very similar

You could check the read counts in your output (columns like `IJC_SAMPLE_1`) to see if you can find any events with counts that you think should be significant

**Comment by forever-happy-h** [comment]
> The script removes replicates that have no read counts for the event from the statistical test. The events in your output could have p value of 1 for a different reason. For example it may be that there are too few read counts for the events, or the read counts for the two sample groups are very similar
> 
> You could check the read counts in your output (columns like `IJC_SAMPLE_1`) to see if you can find any events with counts that you think should be significant

Thank you so much for the quick response, EricKutschera.

I've already solved the problem and it works perfectly!
