### ISSUE TITLE
Maximum number of files to compare

### ISSUE THREAD

**Issue by lsh74** [Xinglab/rmats-turbo#325]
Hello, I would like to know the maximum number of bam files that b1.txt and b2.txt can compare?

**Comment by lsh74** [comment]
And out_rmats has empty files, and output_rmats only has two empty folders split_dot_rmats and tmp，What's the problem, please.

**Comment by EricKutschera** [comment]
I don't know of any limit on the number of files for b1 and b2. There was an issue related to the number of files, but it was fixed in v4.1.2: https://github.com/Xinglab/rmats-turbo/issues/139

Related to the empty output: rMATS should output a section like:
```
read outcome totals across all BAMs
USED: ...
```

If your output files are empty then I would expect the printed output to show a lot of reads failing one of the filters, or for there to be some error message

**Comment by lsh74** [comment]
thank you！I have solved the problem
