### ISSUE TITLE
ImportError: No module named rmatspipeline

### ISSUE THREAD

**Issue by shum-sky** [Xinglab/rmats-turbo#36]
Hi!

I successfully used the ./build_rmats, but now that I am trying to run the program itself, I am getting the following error:

Traceback (most recent call last):
  File "/home/ashumskiy//Programs/rmats-turbo/rmats.py", line 16, in <module>
    from rmatspipeline import run_pipe
ImportError: No module named rmatspipeline

**Comment by EricKutschera** [comment]
Is there a file like `rmatspipeline.so` or `rmatspipeline.cpython-36m-x86_64-linux-gnu.so` in the rmats-turbo directory? If not then there was likely an error during ./build_rmats

If the file is there then the error may be because the `.so` file was created for a different version of Python than the one you are trying to run with. `rmatspipeline.so` is for Python 2. For Python 3 the version number is part of the filename. For example `rmatspipeline.cpython-36m-x86_64-linux-gnu.so` is for Python 3.6

One way you could end up with the wrong `.so` is if you downloaded one of the pre-built `.tar.gz` files from the release page. `./build_rmats` is not meant to be used with those pre-built releases since the `.so` file is already there

**Comment by shum-sky** [comment]
Thanks for the reply, Eric!

I definitely did not download the pre-built files. In fact, I do have a file with the name ' rmatspipeline.cpython-37m-x86_64-linux-gnu.so', which corresponds to the Python version on the computational cluster I am using.

**Comment by EricKutschera** [comment]
What is the command line that you are using? Could you try using the full path for both python and rmats:
`/path/to/python3.7 /path/to/rmats-turbo/rmats.py`

Is your `.so` file in the same directory as rmats.py? Could you try running from that same directory?

If that doesn't work, could you try starting a python3.7 interpreter in the same directory as the `.so` and trying to interactively do `from rmatspipeline import run_pipe`?

**Comment by shum-sky** [comment]
Eric, it turned out that problem was arising because when using the queuing command in the cluster, by default the cluster used Python 2, not Python 3. When I fixed the path, it worked. Thanks for the insight!

**Comment by zzzygolden** [comment]
> Eric, it turned out that problem was arising because when using the queuing command in the cluster, by default the cluster used Python 2, not Python 3. When I fixed the path, it worked. Thanks for the insight!

Hi, my situation was the same as yours. I started a python3.10 interpreter in the same directory as the `.so` and tryed to interactively do `from rmatspipeline import run_pipe`, it was ok. I wanna know how you fixed the path, is it in `run_rmats`? It didn't work as I tryed.
