### ISSUE TITLE
conda installation version

### ISSUE THREAD

**Issue by neelroop** [Xinglab/rmats-turbo#44]
I was able to get rMATS up and running via a conda installation. I used this link:
https://anaconda.org/bioconda/rmats
And it states the current version is 4.1.0. However, in my download, it says the conda package is rmats-4.0.2 and when I use rmats.py --version I get v.3.1.0.

I assume the conda package number doesn't correspond to the rMATS package number? Or perhaps I am doing something wrong. If there is there a conda install for v4.1.0, I would appreciate any tips you have on obtaining it. If there isn't, could we get one?

**Comment by EricKutschera** [comment]
It may be that conda was not configured for the conda-forge channel when you installed rMATS.

4.1.0 requires conda-forge for some of its dependencies, but I think 4.0.2 can be installed without conda-forge. You could try installing again, but with this command: `conda install -c conda-forge -c bioconda rmats=4.1.0`

It could also be that some other package in your conda environment had a dependency conflict which prevented 4.1.0 being installed by conda. If you specify `rmats=4.1.0` in the conda install command then conda should report what the dependency conflict is rather than install an older version of rMATS

**Comment by neelroop** [comment]
That was very helpful. It resolved my issue. Might I suggest mentioning the conda option for installation on your main page? It is much easier than the other methods. Thank you!

**Comment by neelroop** [comment]
*I should clarify, you do have the conda option for building rMATS, but just installing the whole thing with conda is much easier.
