### ISSUE TITLE
results from fromGTF.novelJunction.[AS_Event].txt

### ISSUE THREAD

**Issue by SofiaZhangtj** [Xinglab/rmats-turbo#49]
Hi Eric,
Sorry, I don't quite understand the results in fromGTF.novelJunction.[AS_Event].txt file. Is this means some novel junctions can be found in my RNA samples but not annotated by GTF file? Or any junctions can be found by my samples in spite of GTF annotation?
Best regards,
Sofia

**Comment by EricKutschera** [comment]
An event in fromGTF.novelJunction.[AS_Event].txt must have at least one junction which is not annotated in the GTF file, but which is supported by the RNA data. That unannotated junction is the "novel junction".

For example, suppose a GTF file has only 1 transcript for a gene and that transcript has three exons. If the RNA data has reads which go directly from the first exon to the last exon (skipping the middle exon) then the junction between the first and last exon is a "novel junction". This is because the junction is not annotated in the GTF, but the junction is supported by the RNA data. In that case the event would be written to fromGTF.novelJunction.SE.txt

**Comment by SofiaZhangtj** [comment]
Thank you very much. I really appreciate this.
