### ISSUE TITLE
summary.txt

### ISSUE THREAD

**Issue by jingjiai** [Xinglab/rmats-turbo#54]
Hello,
I want to run summary.py to generate a summary.txt by this command:
nohup python summary.py output_dir /home/lvjin/rmats-turbo/CGGA/CGGA_test/ --inc-level-diff-cutoff 0.1 --summary-path /home/lvjin/rmats-turbo/CGGA/summary/ --summary-prefix /home/lvjin/rmats-turbo/CGGA/summary/summary &
but it's wrong:
summary.py: error: unrecognized arguments: /home/lvjin/rmats-turbo/CGGA/CGGA_test/
so what can I do?
Thanks!

**Comment by EricKutschera** [comment]
`output_dir` is being interpreted as the actual path instead of `/home/lvjin/rmats-turbo/CGGA/CGGA_test/`. Also `--summary-path` and `--summary-prefix` should not be used at the same time. If `--summary-prefix {/prefix/path}` is used then the actual output file will be something like `/prefix/path_FDR_0.05_IncLevelDifference_0.1.txt`. `--summary-path {/full/path.txt}` causes `--summary-prefix` to be ignored.

You could try this command:
`python summary.py /home/lvjin/rmats-turbo/CGGA/CGGA_test/ --inc-level-diff-cutoff 0.1 --summary-prefix /home/lvjin/rmats-turbo/CGGA/summary/summary`

**Comment by jingjiai** [comment]
Thanks for quick response! 
I have run it successfully!
