### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by yx-xu** [Xinglab/rmats-turbo#6]
Hi!
I met ERROR when ./build_rmats, could someone help me about this? I have already installed the required dependencies. The error is : 
![image](https://user-images.githubusercontent.com/57080322/83971716-7cb40e80-a90f-11ea-898c-825288d85005.png)
![image](https://user-images.githubusercontent.com/57080322/83971740-981f1980-a90f-11ea-8502-fc8017968d20.png)

Thanks for your help!

**Comment by EricKutschera** [comment]
I think these two lines are saying that the fortran and blas libraries that you have installed are incompatible:

```
/usr/bin/ld: warning: libquadmath.so.0, needed by /home/long/anaconda2/lib/libgfortran.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libgfortran.so.3, needed by /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libblas.so, may conflict with libgfortran.so.4
```

My guess is that /home/long/anaconda2/lib is in your LD_LIBRARY_PATH which is telling the compilation to use the anaconda2 installed fortran libraries instead of the regular gcc fortran libraries (maybe at /usr/lib/gcc/x86_64-redhat-linux/4.4.7/libgfortran.so) that blas wants.

If /home/long/anaconda2/lib is in LD_LIBRARY_PATH then you could try removing that, getting a fresh copy of the source code and building from that

**Comment by yx-xu** [comment]
Thanks a lot EricKutschera~
