### ISSUE TITLE
paired stat model and different rmats version

### ISSUE THREAD

**Issue by woshi0655** [Xinglab/rmats-turbo#64]
Hi, I have some confused  when I run the rmats. I now try to find different splicing events between two different sex plant samples.
1、when I used the rmats3.2.5 , if I run the data using the paired stat model, then I will got about five thousands differents events and the most popuplar different splicing event is the RI,  which was reports to be the most popular splice type in plant. Then, because some of my sample only have two replicates, so I needed to work with  the unparied stastic model, I got fewer splicing events (about 1 thousand , fdr <0.01) and the most poplar splicing events is the SE type. So I do not know, why?
2、 I also try the rmats4, but I got no results, although these data worked when I used the rmats3.2.5.

paired stat model          
           F         M            
A3SS | 1090 | 1002
A5SS | 635 | 419
SE | 567 | 351
RI | 2588 | 2301
MXE | 60 | 62

unpaired stat model
          F        M
A3SS | 250 | 149
A5SS | 212 | 75
SE | 922 | 630
RI | 225 | 88
MXE | 8 | 8

**Comment by EricKutschera** [comment]
1. It seems like the difference in results could be due to the different samples that you ran. It could also be from the different model (paired and unpaired). The 3.2.5 version of rmats is not the recommended version anymore and investigating any issues in that version is not a priority
2. How did you install rmats 4 (from a recent commit, from conda, ...)? What was the command that you ran? Was there an error or were the output files just empty (only headers)?

**Comment by woshi0655** [comment]
Hi. I install the rmats4 from conda. I only got the headers with no error. I use the following commmand.
python2.7 ~/softinstall/conda/bin/rmats.py --b1 b1.txt --b2 b2.txt --gtf splice1.gtf  -t paired --readLength 150 --nthread 24 --od rmatsresult --tmp tmp_output  --novelSS

**Comment by EricKutschera** [comment]
If there were no errors, but only headers in the output, then that means that rmats did not find any events to report based on your inputs. That could happen for many reasons including:

* the alignments in the BAM files did not match `--readLength`
* the alignments had unexpected cigar operations (such as clipping)
* the alignments did not match up with the GTF

You could try running with `--variable-read-length` (the new version of rmats is by default more strict than older versions about matching `--readLength`). You could also try starting with fastq files so that rmats will do the alignment step. That could resolve any unexpected behavior from creating the BAM files outside of rmats https://github.com/Xinglab/rmats-turbo#starting-with-fastq-files

If you are able to build from the latest source code with https://github.com/Xinglab/rmats-turbo#build then you can check the `{datetime}_read_outcomes_by_bam.txt` output file in the `--tmp` dir to see if the alignments from the BAM files are being ignored for some reason. The latest code also includes a new parameter which may allow alignments that were ignored to be used: `--allow-clipping`

**Comment by woshi0655** [comment]
Hi Eric, I have got all the results now, thank you so much for your help.
