### ISSUE TITLE
Non annotated intron retention quantification

### ISSUE THREAD

**Issue by ngualand** [Xinglab/rmats-turbo#65]
Hi,
I have use rMATS with the --novelSS option,
I was wonder whether rMATS is able to test all introns for potential retention or it is restricted to those annotated as "retained introns" in the gtf file. 
Why some introns are not present in the output file RI.MATS.JC[EC].txt, is that because they do not have enough reads to be quantified or there are other filters applied?

Thank you very much for the help.

**Comment by EricKutschera** [comment]
rMATS does not test all introns for potential retention. It will only check introns which are annotated in the GTF file. See https://github.com/Xinglab/rmats-turbo/issues/17 for some additional details

All of the retained intron events that rMATS identified as possible are in fromGTF.RI.txt. The reads from the BAM files are then checked against the fromGTF.RI.txt events to get inclusion and exclusion counts. There is a filter applied to the inclusion and exclusion counts that an event needs to pass in order to end up in RI.MATS.JC.txt. The filter is for the bare minimum evidence to support alternative splicing between the two groups. The filter criteria are: https://github.com/Xinglab/rmats-turbo/blob/5a9ea254bf5e8b9204d73a5c4f08630827480181/rmats.py#L304

* at least one read in group 1 (inclusion or exclusion)
* at least one read in group 2 (inclusion or exclusion)
* at least one inclusion read (in group 1 or group 2)
* at least one exclusion read (in group 1 or group 2)

If you run rMATS with --statoff then the filter is not applied

**Comment by ngualand** [comment]
Thank you very much!
