### ISSUE TITLE
Conda rmatspipeline

### ISSUE THREAD

**Issue by JojoZhangxinye** [Xinglab/rmats-turbo#67]
I installed it via conda `conda install rmats`
but when I run rmats.py, it had an error:
```
Traceback (most recent call last):
  File "/home/xyzhang/Software/miniconda3/envs/RNA-seq/bin/rmats.py", line 16, in <module>
    from rmatspipeline import run_pipe
ModuleNotFoundError: No module named 'rmatspipeline'
```
I've saw the #36 but still don't konw how to solve it 
(The version of python is 3.6.11)

**Comment by EricKutschera** [comment]
It may be that your environment is not setup to find the correct version of python. You can check what paths are being found for rmats.py and python to see if they are the same. If your conda environment is activated then I would expect you to see results like

```
which python
/home/xyzhang/Software/miniconda3/envs/RNA-seq/bin/python

which rmats.py
/home/xyzhang/Software/miniconda3/envs/RNA-seq/bin/rmats.py
```

The first line of rmats.py is `#!/usr/bin/env python` so it will use whatever version of python it finds (which may not be the one from your conda environment)

You could check that the conda version of python is compatible by using the explicit path of python to call rmats.py:
`/home/xyzhang/Software/miniconda3/envs/RNA-seq/bin/python /home/xyzhang/Software/miniconda3/envs/RNA-seq/bin/rmats.py`

**Comment by Biojenifer** [comment]
Hi!

I am also getting this error and when doing the code you indicate I get the following:

`which python
/mnt/netapp2/programs/environments/python/rMATS/rmats_turbo_v4_1_1/conda_envs/rmats/bin/python

which rmats.py
/usr/bin/which: no rmats.py in (/mnt/netapp2/programs/environments/python/rMATS/rmats_turbo_v4_1_1/rmats.py):
`

**Comment by EricKutschera** [comment]
The original post in this thread is related to installing rmats from conda. The recommended command for that is: `conda install -c conda-forge -c bioconda rmats=4.1.1`. In that case `which python` and `which rmats.py` should show the same path since both python and rmats.py will be installed to the `bin/` directory of the conda environment

In your case, it looks like you installed rmats from source using `./build_rmats --conda`. When installed that way rmats.py is not expected to be found using `$PATH`. Instead you can run rmats by using the `./run_rmats` script from the source code directory

Also the error from `which rmats.py` shows that `PATH=/mnt/netapp2/programs/environments/python/rMATS/rmats_turbo_v4_1_1/rmats.py`, but PATH expects directories, not files

**Comment by Biojenifer** [comment]
Ok, I see.

So what I did to solve the problem was: `export PATH=/mnt/netapp2/programs/environments/python/rMATS/rmats_turbo_v4_1_1:$PATH` before launching rmats and now it worked.

Thanks a lot for your help!

**Comment by NicolaiLolansen** [comment]
Just to add to this now closed issue.

If you run rmat.py using `conda run rmats.py` it will work without having to worry about python paths etc.
