### ISSUE TITLE
Error in the paired statistics section

### ISSUE THREAD

**Issue by hust-yyan** [Xinglab/rmats-turbo#69]
Hello, I recently ran into some problems in the statistical analysis when I used rmats-turbo to analyze differential alternative spling events. The software version I used is V4.1.0. Here is my command: rmats.py  --b1 $indir/b1.txt --b2 $indir/b2.txt --gtf  $gtf --task both  \
--od  $outdir  --tmp $outdir/rmats_tmp -t paired --readLength 150  --variable-read-length --libType fr-firststrand   \
--cstat 0.0001 --paired-stats  --novelSS  --nthread 4
b1.txt and b2.txt are the results of STAR 
I get the following error message:
![image](https://user-images.githubusercontent.com/54279739/102169812-f7b53d80-3ecd-11eb-9d16-ca2e84bd45e8.png)
Thank you!

**Comment by EricKutschera** [comment]
It looks like you may not be using the version of PAIRADISE that rmats expects. How did you install PAIRADISE?

rmats expects the version of PAIRADISE available on github. If you use the build_rmats script then it will download and install that version of PAIRADISE: https://github.com/Xinglab/rmats-turbo/blob/master/build_rmats#L65 . You could try reinstalling PAIRADISE to see if the error is resolved

Regarding the error message, it seems like this is the main error:
```
Error in if ((abs(ll.new.u - ll.old.u) < tol) & (abs(ll.new.c - ll.old.c) < :
  missing value where TRUE/FALSE needed
```
That looks like this line from the source code https://github.com/Xinglab/PAIRADISE/blob/master/pairadise/src/pairadise_model/R/pairadise.R#L338 and the error indicates that one of the values in the conditional is NA. I'm not sure how that could happen. If you can share your `JC.raw.input.SE.txt` from the rmats output directory then I could try to reproduce the error

**Comment by hust-yyan** [comment]
Thank you very much for your answer！
This is JC. Raw. Input. SE. TXT

**Comment by hust-yyan** [comment]
Thank you very much for your answer
This is JC. Raw. Input. SE. TXT

**Comment by EricKutschera** [comment]
It looks like JC.raw.input.SE.txt was intended to be included in your previous comment, but I don't see the file. Maybe there was an error when attaching the file. Could you try uploading that file again?

**Comment by hust-yyan** [comment]
Sorry, this file is too big, it was not uploaded successfully before, this is the result of uploading again<iframe src="https://onedrive.live.com/embed?cid=CB0DD426002DC65C&resid=CB0DD426002DC65C%21454&authkey=ACKWQbfFCJtpDa0" width="98" height="120" frameborder="0" scrolling="no"></iframe>

**Comment by hust-yyan** [comment]
Sorry, this file is too big, it was not uploaded successfully before, this is the result of uploading again[file](https://1drv.ms/t/s!AlzGLQAm1A3Lg0Z_TpYCmu8QmjuI?e=g9qT6O)

**Comment by EricKutschera** [comment]
I was not able to reproduce that error when running your file using the latest version of PAIRADISE on github. It seems like your version of PAIRADISE is not compatible with rmats

You could try installing the github version and re-running. To install you should be able to run these commands from build_rmats https://github.com/Xinglab/rmats-turbo/blob/master/build_rmats#L71

* `git clone https://github.com/Xinglab/PAIRADISE.git`
* `Rscript install_r_deps.R`

Since you already have PAIRADISE installed, the script will only install any missing dependencies. But you can manually install from the cloned source code by starting `R` and running (https://github.com/Xinglab/rmats-turbo/blob/master/install_r_deps.R#L25):
`install.packages("./PAIRADISE/pairadise/src/pairadise_model/", repos=NULL)`

The output with the new version should look like:
```
Loading required package: nloptr
Loading required package: doParallel
Loading required package: foreach
Loading required package: iterators
Loading required package: parallel
Loading data...
A total of 967511 exons will be tested.
Preparing {n} clusters for parallel processing....
Starting analysis.
```

You should see a `pairadise_status.txt` file being written in the `--tmp` dir under `tmp_dir/JC_SE/`. That file reports the incremental progress. Since your file is large (967511 events) it will take a while to finish. It is a known issue that the paired model is not very fast: https://github.com/Xinglab/rmats-turbo/issues/5

You can run PAIRADISE with more threads by giving the `--tstat` argument to rmats. That should help, but it will still take a while to complete

**Comment by hust-yyan** [comment]
thank you very much
