### ISSUE TITLE
Maximum number of events with annotated junctions

### ISSUE THREAD

**Issue by meettel** [Xinglab/rmats-turbo#79]
Hi,
I am using Rmats to analyse single samples using the --statoff parameter, which should allow me to avoid filtering out any event annotated in the reference gtf.
By subtracting the number of events with novel junctions obtained from the fromGTF.novelJunction.[AS_type].txt files to the total number of events in the fromGTF.[AS_type].txt files I would expect to obtain the total number of events with annotated junctions (equal for all samples). On the contrary, this number differs between samples.
Could you please indicate me where my mistake is?
Thank you very much for your help.

**Comment by EricKutschera** [comment]
The procedure you suggest for checking the total number of events that are given in the input annotation file is reasonable. fromGTF.[AS_type].txt should contain all events, fromGTF.novelJunction.[AS_type].txt should contain those events that required a read supporting a novel (unannotated) junction, and fromGTF.novelSpliceSite.[AS_type].txt should contain those events which required a read supporting a novel (unannotated) splice site. If you run with `--statoff` then no events should be filtered out

If you run without `--novelSS` then `num_events(fromGTF.novelSpliceSite.[AS_type].txt)` should be 0 and `num_events(fromGTF.[AS_type].txt) - num_events(fromGTF.novelJunction.[AS_type].txt)` should be the number of annotated events

I tried to verify this by running rmats, but I found that there is an issue. If the annotation includes multiple genes that cover the same region, and one of the genes has the event fully annotated (no novel junction needed), but another gene has the exons annotated but not all of the junctions in the event (novel junction is needed) then rmats may or may not classify the event as novelJunction. It depends on whether the input BAMs have a supporting read

I found an example where my annotation file included a gene (SLC25A32) with an annotation for both the inclusion and skipping isoform of an SE event. The annotation file also had a different gene (AC012213.5) which had an annotation for only the inclusion isoform of that same SE event. I ran rmats with one BAM file which had a read supporting the skipping isoform for that SE event and the event ended up in the novelJunction file. I ran rmats again with a different BAM file which did not have a read supporting the skipping isoform of that SE event and the event was only in the main fromGTF file

In the rmats code, events are detected in a loop that goes over each gene: https://github.com/Xinglab/rmats-turbo/blob/master/rMATS_pipeline/rmatspipeline/rmatspipeline.pyx#L2805

When a particular gene is being processed, if that gene does not have the event fully annotated, but the event can be detected using a read supporting the novel junction, then the event will be marked as novelJunction. When there are multiple annotated genes for the same event, then any gene where the event is novelJunction will overrule a gene that marks the event as annotated. That is probably not the ideal behavior and I'll look into a change to improve this issue with conflicting genes

**Comment by meettel** [comment]
Hi Eric,
thank you very much for your detailed answer.
I understand the issue that you presented and I tried to verify whether it justifies the discrepancy observed in my data.
In doing so, I took the set of events shared by two of my samples based on their coordinates and I checked their annotation class (annotated, novelJN or novelSS, indeed I run Rmats with also the --novelSS option).
Your explanation seems to fully address the different annotation of events involved by novelSS, indeed all these events have a different GeneID between the two samples.
On the contrary, considering events with discordant annotation between samples and involved by a novelJN, the vast majority of them (~98%) have the same GeneID. For the specific case I am studying, this means that I still have 961 events with exactly the same coordinates and GeneID between the two samples that in one case are considered as "annotated" and in the other one as "novelJN".
By checking manually some of these events in IGV I would say they are annotated, but this might not hold true for all of them.
Thank you again for your help.

**Comment by EricKutschera** [comment]
The GeneID column in the fromGTF files is set based on one of the genes which rmats used to detect the event. The final GeneID is not necessarily the GeneID which determined whether the event was classified as annotated or novel. The code roughly does the following

```
detected_events = empty_map_of_events_with_details()
for each gene_id
  event, event_is_novel_junction = try_find_event(gene_id)
  if not event:
    continue

  if event not in detected_events:
    detected_events.add(event)
    detected_events[event].gene_id = gene_id

  if event_is_novel_junction:
    detected_events[event].is_novel_junction = true
```

The code isn't exactly written like that, and the code is not expecting an event to be detected in multiple genes, but that pseudocode describes the behavior. The genes are in a hash map so the order could change, but for a particular GTF file and rmats build, the order of iteration may be consistent. Let's say there are 2 genes: g_annotated and g_nj and there are two input files i_annotated_only and i_nj where only i_nj has the supporting read for the junction that is not annotated for g_nj. No matter what the iteration order is, the event will be in the fromGTF.novelJunction file for i_nj but not i_annotated_only

If the iteration order happens to process g_annotated first, then for both inputs the event will be first detected under g_annotated and reported in the fromGTF file with the GeneID from g_annotated

If the iteration order happens to process g_nj first, then for i_annotated_only the event will not be detected when g_nj is processed and it will not be added to detected_events until a later iteration of the loop when g_annotated is processed. So for i_annotated_only the reported GeneID is still from g_annotated. For i_nj, the event will be detected when g_nj is processed and it will be added to detected_events and the reported GeneID will be from g_nj

You could find the set of annotated events by running rmats with a GTF file and with a mostly empty input. If you use --statoff and a file in --b1 that is empty (attached as .gz due to upload restriction but empty.bam is a bam with no alignments [empty.bam.gz](https://github.com/Xinglab/rmats-turbo/files/5850079/empty.bam.gz)) then all detected events must be annotated because there are no supporting reads

**Comment by meettel** [comment]
Thank you very much Eric for the explanation, I understood now.
Running Rmats with the empty bam returned all the annotated events I was looking for.
Thanks again
