### ISSUE TITLE
Different libType has no effect on the final result

### ISSUE THREAD

**Issue by LucoLab** [Xinglab/rmats-turbo#80]
Changing fr-firststrand to fr-secondstrand in rmats makes no changes in the final results.
I know for sure my library is pairend & stranded.
I tested my library type with salmon ([here](https://salmon.readthedocs.io/en/latest/library_type.html) and it's ISR meaning fr-firstrand using rmats vocabulary.
But it's weird that when you rerun same analysis setting fr-secondstrand you end with the exact final results. No ?

**Comment by EricKutschera** [comment]
In the current version of rmats, `--libType` is only used for exon reads. Those exon reads will be assigned a strand based on being the first or second read in the pair and whether the alignment is reverse complemented: https://github.com/Xinglab/rmats-turbo/blob/5a9ea254bf5e8b9204d73a5c4f08630827480181/rMATS_pipeline/rmatspipeline/rmatspipeline.pyx#L587

Later, when the exon reads are checked to see if they support specific events, the assigned strand must match the expected strand for the event in order to contribute to the count: https://github.com/Xinglab/rmats-turbo/blob/5a9ea254bf5e8b9204d73a5c4f08630827480181/rMATS_pipeline/rmatspipeline/rmatspipeline.pyx#L1876

The code does not do strand checking for reads which include a splice junction. Because of that, I would expect only the JCEC output files and not the JC output files to change based on the `--libType` parameter. That behavior is probably not ideal

Also, In older versions of rmats, the `--libType` argument was passed directly to TopHat to align input fastq files. Now rmats uses STAR to algin fastq files and does not use that parameter anymore
