### ISSUE TITLE
stat only update missing from conda

### ISSUE THREAD

**Issue by bio-scott** [Xinglab/rmats-turbo#82]
Hi, 

I am running rmats v4.1.0 installed from conda. 

It is mostly running great, except it can't seem to handle running the statistical model separately with `--task stat `. It returns the error: `rmats.py: error: argument --task: invalid choice: 'stat' (choose from 'prep', 'post', 'both', 'inte')`

It looks like the conda source hasn't been updated since several months prior to the "stat only mode" update. Is there any way to get this updated feature through conda? 

(I have tried git clone and then building, but this has led to numerous other environment problems that are difficult to diagnose, so conda is preferred)
 
Thanks!

**Comment by EricKutschera** [comment]
The current version available with `conda install -c conda-forge -c bioconda rmats` is from the github 4.1.0 release https://github.com/Xinglab/rmats-turbo/releases

To update the bioconda package, we would need to create a new github release and update the bioconda recipe: https://github.com/bioconda/bioconda-recipes/blob/4d8723c5b52dd4310934da589de887198784e7b6/recipes/rmats/meta.yaml#L9

It has been a while since the 4.1.0 release and I think making a new release makes sense. We'll take a look at the pending changes that we may want to include in the next release and make sure the code is in good shape for an official release. I think we could make the next release soon, but I don't know exactly when

In the meantime, if you are unable to build using the source code, you could try using the docker image: https://hub.docker.com/r/xinglab/rmats/tags?page=1&ordering=last_updated

Updating the docker image is not as big of a process as updating the bioconda package and I've added docker images that are tagged with the hash of the github commit that they were built from. There is an image built from the latest commit hash (43f5beeb6c289f2ac8f0741a986933aa4f387b16) which is the commit which added the `--task stat` feature

**Comment by bio-scott** [comment]
Hi Eric, 

Thanks for the explanation. This is what I figured. I will also try the docker image as you suggest.

On this note, if I have more than two samples and manually set up all of the pair-wise comparisons using the default / full method (pre, post and stat all in a single step), will the results be the same as the recommended method (separate steps for pre, pos, and stat) for more than two samples? i.e. is this just provided for convenience, or do the stats (e.g. FDR) take all of the possible comparisons from a single post file into account?

Thanks again!

**Comment by EricKutschera** [comment]
The results could be different for the two approaches:
1. run samples 1 and 2 in a single default run (--task both)
2. run samples (1, 2, 3) in prep steps, then (1, 2, 3) in a single post step, then --task stat for just samples 1 and 2

In approach 1, when the post step detects the set of events it doesn't know about sample 3 and so will not detect any novel events which require supporting reads that are only available in sample 3. In approach 2, the post step has all the information and so will potentially detect more novel events. Also, the shared set of events which are detected in both approaches may have different IDs because the IDs are assigned based on the order in which the events are detected

The extra events should partially be filtered out during the --task stat step. The events are filtered out if one of the groups being compared does not have any reads for the event (inclusion or skipping) or if neither group has a read for the inclusion form or neither group has a read for the skipping isoform: https://github.com/Xinglab/rmats-turbo/blob/43f5beeb6c289f2ac8f0741a986933aa4f387b16/rmats.py#L321
For events where the additional sample (sample 3) in the combined post step was the only sample with supporting reads for the skipping isoform of an event and that event is novel because of the skipping isoform then only approach 2 will detect the event. But the event will be filtered out because sample 1 and 2 will not have a read for the skipping isoform. However, it is possible for an event to not be detected in approach 1 because one of the inclusion junctions is novel and only found in sample 3. In this case the non-novel inclusion junction and the skipping junction have supporting reads in samples 1 and 2 so the event will not be filtered out in approach 2 even though it is not detected in approach 1. For example the left inclusion junction of the SE event in the diagram from the README could be the novel junction in sample 3: https://github.com/Xinglab/rmats-turbo/tree/43f5beeb6c289f2ac8f0741a986933aa4f387b16#output

If extra events in approach 2 pass the filter then they would impact the FDR calculation. That is a downside of approach 2. A benefit of approach 2 is that there is less computation since only a single prep step for each input and only a single post step are needed. Another benefit is that the event IDs will be the same for all comparisons. There is a code change that has not been merged into the main branch yet that partially addresses the downside of these extra events by reporting the counts for individual junctions. That change would make it easy to identify events that do not have reads supporting one of the inclusion junctions: https://github.com/Xinglab/rmats-turbo/pull/41
