### ISSUE TITLE
Fix Makefile: file might not exists

### ISSUE THREAD

**Issue by ccoulombe** [Xinglab/rmats-turbo#92]
`rm *.so *.so.* *.dylib` should be `rm -f` as `dylib` might not exists.

https://github.com/Xinglab/rmats-turbo/blob/7f38d6bcf32894a87bd767408f30bc055d9ba15d/Makefile#L4

**Comment by EricKutschera** [comment]
Thanks for the suggestion. As the Makefile currently is, it should still remove any existing files and print out a message like "rm: cannot remove ‘*.dylib’: No such file or directory". Since the line starts with `-` it will ignore the error and continue on with the build

I've opened a PR to make the suggested change
