### ISSUE TITLE
Run rMATS for 3 samples/conditions at once

### ISSUE THREAD

**Issue by mariakondili** [Xinglab/rmats-turbo#96]
Hello! This is not an issue but more of a question on functionalities or rMATS.
I d like to know if it's possible to run for comparing the splicing events of WT vs Treatment1 vs Treatment2, all at once, 
and obtain a table with Incl_Level_WT, Incl_Level_Treatment1, Incl_Level_Treatment_2, and the 2 respective Incl_Differences.
Something like having a --b3 option, for .bam files. 

I saw that when I run separately  WT-vs-Treat1,  WT-vs-Treat2 ,  the Incl_Level_WT, of these two tables is not same for some events. 
Moreover, I have to do data mining to find the genes and events that are common on 1st and 2nd comparison, but we are more interested in having the values of splicing for each exon along all 3 conditions. 
Is there a way to run rMATS with existing options in a way that I obtain the table I want , by using only --b1, --b2 ? 
e.g  --b1 = WT_1,WT_2, WT_3 ,  --b2 Treat1a, Treat1b, Treat1c  ==>and then,
 the results of these   over  --b2 Treat2a, Treat2b, Treat2c  ?
Thanks in advance for any suggestion

**Comment by EricKutschera** [comment]
You can first process all of the input bams with one or more `--task prep` steps. Then combine all of the prep output into a single `--task post` step. Finally do two separate runs of `--task stat`, one for WT vs Treatment1 and another for WT vs Treatment 2. You'll get a set of output files for each run of `--task stat`, but they will be based on the same set of event definitions from the `--task post` step so you can match up the rows easily

Here is the section of the README that is related to this: https://github.com/Xinglab/rmats-turbo/tree/v4.1.1#running-the-statistical-model-separately

**Comment by mariakondili** [comment]
Thanks for the help ! I got  it ! For the record, briefly  this is what I ran:  
#PREP_step_1 :  ` python rmats.py --b1 ${group1} --b2  ${group2}  --tmp ${outDir_prep}/tmp_1/ --task prep `
#PREP_step_2:  ` python rmats.py --b1 ${group1} --b2  ${group3}  --tmp ${outDir_prep}/tmp_2/ --task prep `
#POST_step :  `python rmats.py --b1 ${group123}  --tmp ${outDir_prep}/combo_tmp/  --task post `
#STATS_step_1 : 
 `python  prepare_stat_inputs.py  --new-output-dir ${outDir_post}/out_gr1_gr2   --old-output-dir ${outDir_post}  --group-1-indices 0,1,2    --group-2-indices 3,4,5 `
`python  rmats.py --od ${outDir_post}/out_gr1_gr2  --tmp ${outDir_post}/out_gr1_gr2/tmp  --task stat `

#STATS_step_2 : 
 `python prepare_stat_inputs.py  --new-output-dir ${outDir_post}/out_gr1_gr3 --old-output-dir ${outDir_post}  --group-1-indices 0,1,2  --group-2-indices 6,7,8` 
`python rmats.py --od ${outDir_post}/out_gr1_gr3  --tmp ${outDir_post}/out_gr1_gr3/tmp  --task stat`

The ID column for the post is same in Stat-step so, we can really nicely follow up the events and their values.

**Comment by macsalvin** [comment]
Hi @EricKutschera,
I would like to compare three groups (as you mention [here](https://github.com/Xinglab/rmats-turbo#running-the-statistical-model-separately) ), in my case KT vs KV and KT vs QT. 
As a final result I would like to have the total number of SE events (I mention just SE as an example) for KT and then the differential SE events for both KT vs KV and KT vs QT. As you can see in Fig.1 and Fig.2 the rows for KT are different for the two comparisons and so the sum for getting the total events (Why there are different rows?). How can I get the total SE events for KT? Should I get it before running the statistical part?

Fig.1 (row 7 is missing)
![Screen Shot 2021-05-24 at 4 35 05 PM](https://user-images.githubusercontent.com/23176893/119405113-c4fa4700-bcae-11eb-9414-64dc5c81c80a.png)


Fig.2 (rows 0,4,5,6 are missing)
![Screen Shot 2021-05-24 at 4 34 56 PM](https://user-images.githubusercontent.com/23176893/119405146-d0e60900-bcae-11eb-84ea-ca4e34c75f35.png)

Here all my steps:

**Running prep and post separately**

**Running prep**
./run_rmats --b1 ALLSAMPLE.txt --gtf Mus_musculus.GRCm38.92.chr.gtf --readLength 150 --nthread 28 --od output --tmp tmp_output_prep --task prep

**Running post**
./run_rmats --b1 ALLSAMPLE.txt --gtf Mus_musculus.GRCm38.92.chr.gtf --readLength 150 --nthread 28 --od outputPOST --tmp tmp_output_prep --statoff --task post

**Extract information for a specific comparison**

**KTKV**
python rMATS_P/prepare_stat_inputs.py --new-output-dir outputKTKV --old-output-dir outputPOST --group-1-indices 0,1,2,3,4 --group-2-indices 5,6,7
**KTQT**
python rMATS_P/prepare_stat_inputs.py --new-output-dir outputKTQT --old-output-dir outputPOST --group-1-indices 0,1,2,3,4 --group-2-indices 8,9,10,11,12,13

**Running the statistical part**

**KTKV**
./run_rmats --od KTKV --tmp tmpKTKV --task stat

**QTQV**
./run_rmats --od QTQV --tmp tmpQTQV --task stat


Thank you so much for your help

**Comment by EricKutschera** [comment]
When the statistical model is run (--task stat), the count files are first filtered to remove rows where there is not enough information (zero counts). Here is the code: https://github.com/Xinglab/rmats-turbo/blob/v4.1.1/rmats.py#L322

It filters out a row unless:
* group 1 has at least one count (either inclusion or skipping)
* group 2 has at least one count (either inclusion or skipping)
* at least one of the two groups has at least one inclusion count
* at least one of the two groups has at least one skipping count

The count files were not filtered in the post step since you ran that step with --statoff. You can look at the count files in outputPOST to see the rows that were filtered out in --task stat

**Comment by macsalvin** [comment]
Thank you very much @EricKutschera

**Comment by yutaixian** [comment]
> Thanks for the help ! I got it ! For the record, briefly this is what I ran: #PREP_step_1 : `python rmats.py --b1 ${group1} --b2 ${group2} --tmp ${outDir_prep}/tmp_1/ --task prep` #PREP_step_2: `python rmats.py --b1 ${group1} --b2 ${group3} --tmp ${outDir_prep}/tmp_2/ --task prep` #POST_step : `python rmats.py --b1 ${group123} --tmp ${outDir_prep}/combo_tmp/ --task post ` #STATS_step_1 : `python prepare_stat_inputs.py --new-output-dir ${outDir_post}/out_gr1_gr2 --old-output-dir ${outDir_post} --group-1-indices 0,1,2 --group-2-indices 3,4,5 ` `python rmats.py --od ${outDir_post}/out_gr1_gr2 --tmp ${outDir_post}/out_gr1_gr2/tmp --task stat `
> 
> #STATS_step_2 : `python prepare_stat_inputs.py --new-output-dir ${outDir_post}/out_gr1_gr3 --old-output-dir ${outDir_post} --group-1-indices 0,1,2 --group-2-indices 6,7,8` `python rmats.py --od ${outDir_post}/out_gr1_gr3 --tmp ${outDir_post}/out_gr1_gr3/tmp --task stat`
> 
> The ID column for the post is same in Stat-step so, we can really nicely follow up the events and their values.

Excuse me, may I have a question? Do you mean your --b1 group1 contains the bam file of WT_1,WT_2, WT_3? --b2 group2 contains the bam file of Treat1a, Treat1b, Treat1c？
besides，in the post step --statoff is necessary？ or can you tell me your code clearly, thank you very much~ I am a new user.
and if I have a WT and three treatment can I just use twice post_step like#PREP_step_1 : `python rmats.py --b1 ${group1} --b2 ${group2} --tmp ${outDir_prep}/tmp_1/ --task prep` #PREP_step_2: `python rmats.py --b1 ${group3} --b2 ${group4} --tmp ${outDir_prep}/tmp_2/ --task prep?  besides, if I want to obtain the AS events of the for each group at the same time, what should I do?  Thank you very much!

**Comment by EricKutschera** [comment]
https://github.com/Xinglab/rmats-turbo/tree/v4.3.0?tab=readme-ov-file#running-the-statistical-model-separately

In the example all of the bam files are given as `--b1` in the post step. If `--statoff` is not given then the statistical step will still be skipped (with a warning) since there is only 1 group. For the prep step it also makes sense to only use `--b1` since the two groups are only needed for the statistical test

By running all the samples in a single `--task post` rMATS will detect the set of AS events to be used in all of the group comparisons. Then you can follow the instructions from the README to run the statistical test on the different groups to find the significant events for each comparison

**Comment by yutaixian** [comment]
[summary.txt](https://github.com/user-attachments/files/17564944/summary.txt)
> https://github.com/Xinglab/rmats-turbo/tree/v4.3.0?tab=readme-ov-file#running-the-statistical-model-separately
> 
> In the example all of the bam files are given as `--b1` in the post step. If `--statoff` is not given then the statistical step will still be skipped (with a warning) since there is only 1 group. For the prep step it also makes sense to only use `--b1` since the two groups are only needed for the statistical test
> 
> By running all the samples in a single `--task post` rMATS will detect the set of AS events to be used in all of the group comparisons. Then you can follow the instructions from the README to run the statistical test on the different groups to find the significant events for each comparison

Thank you for your reply!  I'm still confused about how to obtain the AS events of only a single experimental group use the  pre and post steps.  I want to firstly abtain the AS events of only a single experimental group(total counts and the number of each type of AS event ), then I will next the statistical test on the different groups to find the significant events for each comparison. any suggestion?
Besides,  The results of directly comparing group1 and group2 are different from those obtained using prep and post.
(https://github.com/user-attachments/assets/29b6a4c2-cefb-4fd3-b3f0-fbf8808bcf2d)
[summary.txt](https://github.com/user-attachments/files/17564960/summary.txt)
[summary1.txt](https://github.com/user-attachments/files/17564955/summary1.txt)

#the code of directly comparing：python rmats.py --b1 ./group1.txt --b2 group2.txt --gtf  Zm-W22-REFERENCE-NRGENE-2.0_Zm00004b.1.gtf -t paired --readLength 150  --nthread 4 --od ./first_test_output/gru1vsgur2 --tmp .gur1vsgur2 
#The code for using the prep and post steps was the same as mentioned above.
why？

**Comment by EricKutschera** [comment]
rMATS detects events based on the `--gtf` and the reads in the bam files. rMATS requires some evidence (either from the `--gtf` or a `bam`) for each exon and splice junction in the event. If run with only a single group (just `--b1`) or with `--statoff` then the events won't be filtered. If the statistical test is run for two groups (`--b1` and `--b2`) then the events are filtered https://github.com/Xinglab/rmats-turbo/issues/96#issuecomment-847847715

If you use the suggested procedure of running all of your samples together in a single `--task post` then rMATS can detect more events. If you run only some of your samples (just two groups) then rMATS can detect fewer events since it doesn't have the reads from all of the bam files and some of those reads may be necessary for rMATS to detect certain events. Using the total number of events when rMATS is run with a single group may not be that meaningful since a lot of those events could be detected from the `--gtf` without any read support in the bam files: https://github.com/Xinglab/rmats-turbo/issues/79#issuecomment-764704152

A possible way to get the event counts for each group is to use the output from all groups run together with `--statoff` and then only count the events which have supporting reads in the specific group that you are counting. You could use the IJC and SJC columns like the filter when the statistical test is run. You could also use the extra columns output with `--individual-counts` and only count events where the specific group has reads to support every junction in the event

**Comment by yutaixian** [comment]
> rMATS detects events based on the `--gtf` and the reads in the bam files. rMATS requires some evidence (either from the `--gtf` or a `bam`) for each exon and splice junction in the event. If run with only a single group (just `--b1`) or with `--statoff` then the events won't be filtered. If the statistical test is run for two groups (`--b1` and `--b2`) then the events are filtered [#96 (comment)](https://github.com/Xinglab/rmats-turbo/issues/96#issuecomment-847847715)
> 
> If you use the suggested procedure of running all of your samples together in a single `--task post` then rMATS can detect more events. If you run only some of your samples (just two groups) then rMATS can detect fewer events since it doesn't have the reads from all of the bam files and some of those reads may be necessary for rMATS to detect certain events. Using the total number of events when rMATS is run with a single group may not be that meaningful since a lot of those events could be detected from the `--gtf` without any read support in the bam files: [#79 (comment)](https://github.com/Xinglab/rmats-turbo/issues/79#issuecomment-764704152)
> 
> A possible way to get the event counts for each group is to use the output from all groups run together with `--statoff` and then only count the events which have supporting reads in the specific group that you are counting. You could use the IJC and SJC columns like the filter when the statistical test is run. You could also use the extra columns output with `--individual-counts` and only count events where the specific group has reads to support every junction in the event

Thank you for your reply. I understood it. But I still confused that after running  all groups  together with `--statoff` how I can get the event counts for each group, for example group1, how can I extract the IJC and SJC of group1?

**Comment by EricKutschera** [comment]
The values in the columns like `IJC_SAMPLE_1` are in the same order as provided in `--b1`: https://github.com/Xinglab/rmats-turbo/issues/263

**Comment by yutaixian** [comment]
> rMATS detects events based on the `--gtf` and the reads in the bam files. rMATS requires some evidence (either from the `--gtf` or a `bam`) for each exon and splice junction in the event. If run with only a single group (just `--b1`) or with `--statoff` then the events won't be filtered. If the statistical test is run for two groups (`--b1` and `--b2`) then the events are filtered [#96 (comment)](https://github.com/Xinglab/rmats-turbo/issues/96#issuecomment-847847715)
> 
> If you use the suggested procedure of running all of your samples together in a single `--task post` then rMATS can detect more events. If you run only some of your samples (just two groups) then rMATS can detect fewer events since it doesn't have the reads from all of the bam files and some of those reads may be necessary for rMATS to detect certain events. Using the total number of events when rMATS is run with a single group may not be that meaningful since a lot of those events could be detected from the `--gtf` without any read support in the bam files: [#79 (comment)](https://github.com/Xinglab/rmats-turbo/issues/79#issuecomment-764704152)
> 
> A possible way to get the event counts for each group is to use the output from all groups run together with `--statoff` and then only count the events which have supporting reads in the specific group that you are counting. You could use the IJC and SJC columns like the filter when the statistical test is run. You could also use the extra columns output with `--individual-counts` and only count events where the specific group has reads to support every junction in the event

I am still confused that how to only count the events which have supporting reads in the specific group that you are counting(quote) after pre and post step. What's the difference between this(count the events which have supporting reads in the specific group) and running "python rmats.py --b1 ${group1} --gtf  --od  --statoff" directly? #418 #275   Running pre and post steps to obtain the number of each splicing event in each group seems more troublesome than running it directly, doesn't it?(becasue it need filter). and  what‘s the mean of use the IJC and SJC columns like the filter when the statistical test is run? Thank you!

**Comment by EricKutschera** [comment]
If you run with just --b1 the output will have a set of AS events which are detected based on the --b1 reads and the --gtf and there is no filter requiring reads to support the events. With just --b1 it doesn't matter if you use --statoff since two groups would be required for the statistical step. The stat filter is not applied unless there are two groups. Since there is no filter, an event being in the output file doesn't mean that the --b1 files "support" or "contain" the event. It could be that the event is detected based on the --gtf and not the reads. You can filter the output files down to events that have read support for the event like the stat filter does by using the IJC_SAMPLE_1 and SJC_SAMPLE_1 columns to require reads supporting both isoforms of the event https://github.com/Xinglab/rmats-turbo/issues/96#issuecomment-847847715

The benefit of running all your samples together in a single `--task post` is that you get the set of all AS events that rMATS can detect from your samples and the --gtf and all of your samples will have their read counts checked for all events. If all you are going to do is get the number of events for each sample group one group at a time then the single `--task post` shouldn't matter. But if you want to compare the events between sample groups then it is useful to have the single set of events so that you can compare the read counts or IncLevel between groups or check which events are only found in a single group or detected in multiple groups

**Comment by yutaixian** [comment]
Thanks for your reply! It's really helpful. But Many studies have shown that intron retention is the main form of alternative splicing in plants(also in Maize). However, my data(Maize) analysis shows that exon skipping is the main event（--b1 --statoff）. Do you have any suggestions?

**Comment by EricKutschera** [comment]
rMATS may not detect many novel intron retention events. These posts have some details:
https://github.com/Xinglab/rmats-turbo/issues/17
https://github.com/Xinglab/rmats-turbo/issues/407

You could try running with --novelSS or modifying the --gtf to get rMATS to detect more RI events
