### ISSUE TITLE
Running statistical model separately 

### ISSUE THREAD

**Issue by sarahwalling** [Xinglab/rmats-turbo#99]
Thanks for your nice tool.  I’d like to be able to run the statistical analysis of rMATS without any dependency on the actual reads or mapping. Specifically, I've computed counts for isoform variant pairs in a few dozen tissues (with biological replicates), in a way that does not produce or depend on BED/SAM files (i.e. I just have counts, but no BED/SAM/BAM files). For each gene of interest, I have two counts (for forms A and B) for each of 10 biological replicates.

It appears that the methods in rMATS are a good approach for a statistical analysis of the count data, and I suspect that the option to “run the statistical model separately” (--task stat) is close to what I need … but that appears to require the input of input files that are of some format that I can’t guess at (the files "fromGTF.[AS].txt" and "{JC,JCEC}.raw.input.[AS].txt"). Is there any more information available about how these are formatted and what information they need to hold? Or, is there a way to adapt rMATS to just take in essentially a csv of counts?

I’ll be grateful your guidance on this - thanks in advance!

**Comment by EricKutschera** [comment]
One way to get examples of the expected format for those files is to run the automated tests for rMATS: https://github.com/Xinglab/rmats-turbo/tree/v4.1.1#test

With those files as an example of the expected format you can make files for your own count data. I've attached [example_files.tar.gz](https://github.com/Xinglab/rmats-turbo/files/6150568/example_files.tar.gz) which has:


* `fromGTF.SE.txt` (from `tests/task_stat/out_all/fromGTF.SE.txt`)
* `JC.raw.input.SE.txt` (`from tests/task_stat/out_all/JC.raw.input.SE.txt`)
* `edited_fromGTF.SE.txt` (I manually edited)
* `edited_JC.raw.input.SE.txt` (I manually edited)

If you create a new directory and put the files from the test output in it then you can run the statistical model with:
`python rmats.py --od /path/to/created_dir_with_files --tmp /path/to/a_new_tmp_dir --task stat`

It will print warning messages saying that it cannot find the JCEC file for the SE events or any of the files for the other events (MXE, A3SS, A5SS, RI), but it will run the statistical model on the SE files that are in the directory. The output file is `/path/to/created_dir_with_files/SE.MATS.JC.txt` which includes copies of the columns from the input files and also these new output columns: PValue FDR IncLevel1 IncLevel2 IncLevelDifference

You could use the `edited_*SE.txt` files as an example of the files you could create from your count data. The files need to be renamed to remove the `edited_` part so that rMATS can find the files. There is a brief description of the columns in the README: https://github.com/Xinglab/rmats-turbo/tree/v4.1.1#output

`edited_fromGTF.SE.txt` has most of the columns set to `0` since they are just copied into the final output file without being used in the statistical model. The ID column needs to start at 0 and increment (0,1,2,...). In `edited_JC.raw.input.SE.txt` the ID column should match with the fromGTF file. The `*JC_SAMPLE_*` columns can be filled in with your count data. The IncFormLen and SkipFormLen columns are used to normalize the counts based on the read length and the lengths of the isoforms. IncFormLen and SkipFormLen are both set to 100 in `edited_JC.raw.input.SE.txt` which essentially disables the normalization. You could calculate the appropriate effective lengths for your data using the calculations in the README: https://github.com/Xinglab/rmats-turbo/tree/v4.1.1#output

**Comment by sarahwalling** [comment]
Thanks for your help! I think I've almost got it, but when I try to run it I get a error message that JC.raw.input.SE.txt is corrupted. Is it necessary for the JC file to contain both inclusion and skipping samples? 

The columns that I have currently are: ID, IJC_SAMPLE_1 through IJC_SAMPLE_35 (for the 35 different tissues we're working with), then IncFormLen and SkipFormLen. Each of the IJC sample columns in each row are filled with two numbers, comma separated - each number representing the raw counts for one of the two isoforms. 

Is this an issue with missing SJC_SAMPLE columns, or is there another reason this format won't work?

**Comment by EricKutschera** [comment]
Here's where the "ERROR: corrupted read count file" is from: https://github.com/Xinglab/rmats-turbo/blob/v4.1.1/rmats.py#L303

rMATS requires the specific columns:
```
ID	IJC_SAMPLE_1	SJC_SAMPLE_1	IJC_SAMPLE_2	SJC_SAMPLE_2	IncFormLen	SkipFormLen
```

The statistical model is designed to compare two groups (sample 1 and sample 2) where each group can have multiple replicates. For each replicate there needs to be two counts, inclusion count (IJC) and skipping count (SJC). The file `JC.raw.input.SE.txt` should look like the following (but with the words replaced by numbers)

```
ID	IJC_SAMPLE_1	SJC_SAMPLE_1	IJC_SAMPLE_2	SJC_SAMPLE_2	IncFormLen	SkipFormLen
0	count_of_isoform_1_group_1_replicate_1,count_of_isoform_1_group_1_replicate_2,...,count_of_isoform_1_group_1_replicate_n	count_of_isoform_2_group_1_replicate_1,count_of_isoform_2_group_1_replicate_2,...,count_of_isoform_2_group_1_replicate_n	count_of_isoform_1_group_2_replicate_1,count_of_isoform_1_group_2_replicate_2,...,count_of_isoform_1_group_2_replicate_n	count_of_isoform_2_group_2_replicate_1,count_of_isoform_2_group_2_replicate_2,...,count_of_isoform_2_group_2_replicate_n	effective_length_of_isoform_1	effective_length_of_isoform_2
```

You have 35 different tissues, but rMATS wants to compare two groups. You could use the rMATS statistical model to compare two of the tissues at a time. In that case `group_1` and `group_2` above would each be a tissue. If you want to compare each tissue to each other tissue then you would need to run rMATS multiple times. Maybe there is a different grouping that makes sense for you, but rMATS needs two groups to compare

**Comment by sarahwalling** [comment]
That was exactly what I needed to get it working, thanks very much!
